language: php
php:
  - 5.6
  - 7 
services:
  - postgresql
script: phpunit -c app/
env:
  - SYMFONY_VERSION=2.8.*
notifications:
  email:
    - ankaraphp06@gmail.com
before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install language-pack-tr
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console doctrine:schema:update --force --env=test
