<?php

namespace Pheetup\UserBundle\Entity;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Pheetup\CoreBundle\Entity\CrudRepositoryInterface;

class GroupRepository extends EntityRepository
    implements CrudRepositoryInterface
{
    public function createEntity()
    {
        $group = new Group('', array());

        return $group;
    }

}
