services:
    pheetup.controller.site.default:
        class: Pheetup\SiteBundle\Controller\DefaultController
        arguments: ["@service_container"]
#    pheetup.site.example:
#        class:     Pheetup\SiteBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
